[general]
chain = "dev"
log4rs_config = "stegos-log4rs.toml"
prometheus_endpoint = "127.0.0.1:9895"
api_endpoint = "127.0.0.1:3149"
data_dir = "testing/node05"
force_check = true

[network]
bind_ip = "127.0.0.1"
bind_port = 10059
advertise_local_ips = false
hashcash_difficulty = 100
seed_nodes = [
    "/ip4/127.0.0.1/tcp/10055",
    "/ip4/127.0.0.1/tcp/10056",
    "/ip4/127.0.0.1/tcp/10057",
    "/ip4/127.0.0.1/tcp/10058",
    "/ip4/127.0.0.1/tcp/10060",
    "/ip4/127.0.0.1/tcp/10061",
]
advertised_addresses = [
    "/ip4/127.0.0.1/tcp/10059",
]