stages:
  - fast_checks
  - test
  - release

# Running fast-checks to notice an author that his pull-request fails our standards.
# This checks should not produce any artifacts
fast_checks:
  stage: fast_checks
  before_script:
    - ./ci-scripts/build.sh builddep
  script:
    - cargo audit
    - cargo fmt --all -- --check
  tags:
    - linux
  image: stegos/rust:nightly-2019-08-05

.test:
  stage: test
  script: ./ci-scripts/build.sh test

test:linux:
  extends: .test
  image: stegos/rust:nightly-2019-08-05
  tags:
    - linux

test:macos:
  extends: .test
  tags:
    - macos

code_coverage:
  stage: test
  image: stegos/rust:nightly-2019-08-05
  script:
    - ./ci-scripts/build.sh coverage_push
  tags:
    - linux
  allow_failure: true

.release:
  stage: release
  dependencies: []
  artifacts:
    expire_in: 1 week
    paths:
      - release/

release:linux:
  extends: .release
  image: stegos/rust:nightly-2019-08-05
  before_script:
     - ./ci-scripts/build.sh builddep
  script:
    - cargo build --bins --release
    - mkdir -p release/linux && mv target/release/{stegos,stegosd,bootstrap} release/linux
  tags:
    - linux

release:macos:
  extends: .release
  before_script:
     - ./ci-scripts/build.sh builddep
  script:
    - cargo build --bins --release
    - mkdir -p release/macos && mv target/release/{stegos,stegosd,bootstrap} release/macos
  tags:
    - macos
