stages:
  - fast_checks
  - test
  - release

# Running fast-checks to notice an author that his pull-request fails our standards.
# This checks should not produce any artifacts
fast_checks:
  stage: fast_checks
  allow_failure: true
  before_script:
    - ./ci-scripts/build.sh builddep
  script:
    - cargo audit
    - cargo fmt --all -- --check
  tags:
    - linux
  image: quay.io/stegos/rust:nightly-2019-10-24

.test:
  stage: test
  script: ./ci-scripts/build.sh test

test:linux:
  extends: .test
  image: stegos/rust:nightly-2019-08-05
  tags:
    - linux

test:macos:
  extends: .test
  tags:
    - macos

# Temporary only build on windows, without running tests
test:windows:
  extends: .test
  script: ./ci-scripts/build.sh build
  tags:
    - win2019

code_coverage:
  stage: test
  image: stegos/rust:nightly-2019-08-05
  script: ./ci-scripts/build.sh coverage_push
  tags:
    - linux
  allow_failure: true

.release:
  stage: release
  dependencies: []
  artifacts:
    expire_in: 1 week
    paths:
      - release/

release:linux:
  extends: .release
  image: stegos/rust:nightly-2019-08-05
  script: ./ci-scripts/build.sh release linux
  tags:
    - linux

release:macos:
  extends: .release
  script: ./ci-scripts/build.sh release macos
  tags:
    - macos

release:windows:
  extends: .release
  script: ./ci-scripts/build.sh release win
  tags:
    - win2019