stages:
  - fast_checks
  - test
  - release

cache:
  key: ${CI_JOB_NAME}
  paths:
    - target

# Running fast-checks to notice an author that his pull-request fails our standards.
# This checks should not produce any artifacts
.fast_checks:
  stage: fast_checks
  allow_failure: true
  cache: {}
  before_script:
    - ./ci-scripts/build.sh builddep
  script:
    - cargo audit
    - cargo fmt --all -- --check
  tags:
    - linux
  image: quay.io/stegos/rust:nightly-2019-10-30

.test:
  stage: test
  script: ./ci-scripts/build.sh test

test:linux_x64:
  extends: .test
  variables:
    RUSTC_WRAPPER: /root/.cargo/bin/sccache
  image: quay.io/stegos/rust:nightly-2019-10-30
  script:
    - env
    - ./ci-scripts/build.sh test
  tags:
    - linux

test:macos_x64:
  extends: .test
  tags:
    - macos

# Temporary only build on windows, without running tests
test:windows_x64:
  extends: .test
  script: ./ci-scripts/build.sh build
  tags:
    - win2019

code_coverage:
  stage: test
  image: quay.io/stegos/rust:nightly-2019-10-30
  script: ./ci-scripts/build.sh coverage_push
  tags:
    - linux
  allow_failure: true

.release:
  stage: release
  dependencies: []
  artifacts:
    expire_in: 3 week
    paths:
      - release/

release:linux-x64:
  extends: .release
  variables:
    RUSTC_WRAPPER: /root/.cargo/bin/sccache
  image: quay.io/stegos/rust:nightly-2019-10-30
  script: ./ci-scripts/build.sh release linux-x64
  tags:
    - linux

release:macos-x64:
  extends: .release
  script: ./ci-scripts/build.sh release macos-x64
  tags:
    - macos

release:windows-x64:
  extends: .release
  script: ./ci-scripts/build.sh release win-x64
  tags:
    - win2019

release:android-x64:
  extends: .release
  image: quay.io/stegos/rust:nightly-2019-10-30
  script: ./ci-scripts/build.sh release android-x64
  tags:
    - linux

release:android-aarch64:
  extends: .release
  image: quay.io/stegos/rust:nightly-2019-10-30
  script: ./ci-scripts/build.sh release android-aarch64
  tags:
    - linux
