[general]
chain = "dev"
log4rs_config = "stegos-log4rs.toml"
prometheus_endpoint = "127.0.0.1:9896"
api_endpoint = "127.0.0.1:3150"
data_dir = "testing/node06/data"
force_check = true

[network]
bind_ip = "127.0.0.1"
bind_port = 10060
advertise_local_ips = false
hashcash_nbits = 4
seed_nodes = [
    "/ip4/127.0.0.1/tcp/10055",
    "/ip4/127.0.0.1/tcp/10056",
    "/ip4/127.0.0.1/tcp/10057",
    "/ip4/127.0.0.1/tcp/10058",
    "/ip4/127.0.0.1/tcp/10059",
    "/ip4/127.0.0.1/tcp/10061",
]
advertised_addresses = [
    "/ip4/127.0.0.1/tcp/10060",
]