[general]
chain = "dev"
log_config = "stegos-log4rs.toml"
prometheus_endpoint = "127.0.0.1:9891"
api_endpoint = "127.0.0.1:3145"
data_dir = "testing/node01"
force_check = true

[network]
bind_ip = "127.0.0.1"
bind_port = 10055
advertise_local_ips = false
handshake_puzzle_difficulty = 100
seed_nodes = [
    "/ip4/127.0.0.1/tcp/10056",
    "/ip4/127.0.0.1/tcp/10057",
    "/ip4/127.0.0.1/tcp/10058",
]
advertised_addresses = [
    "/ip4/127.0.0.1/tcp/10055",
]