[package]
name = "libp2p"
version = "1.0.0"
authors = ["Eugene Chupriyanov <tchu@tchu.ru>"]
edition = "2018"

[dependencies]
futures = "0.1"
libp2p-core = "0.13"
libp2p-swarm = "0.3"
tokio-io = "0.1"
